# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/addcn"
  weibo: "http://weibo.com/addcn"
  rss: "http://blog.uedao.com/atom.xml"
  zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "https://raw.githubusercontent.com/addcn/addcn.github.com/master/statics/images/avatar.png"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: addcn
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  工作记录: http://blog.uedao.com/
  博客巴士: http://addcn.blogbus.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 攻城狮、阅读者、时间管理。07年接触互联网，现在在一家互联网公司从事移动产品开发。

# Extensions
Plugins:
- hexo-generator-feed
- hexo-generator-sitemap
#feed
feed:
  type: atom
  path: atom.xml
  limit: 20
#sitemap
sitemap:
  path: sitemap.xml